server:
  port: 7003
eureka:
  server:
    enable-self-preservation: true  #eureka:eureka.server.enable-self-preservation: false 禁用eureka自我保护机制
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/  #http://${eureka.instance.hostname}:${server.port}/eureka   单机模式
